sudo: false
language: python
python:
  - "2.7"
  - "3.5"
notifications:
  email: false
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda update --yes conda
install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION pip numpy scipy cython nose future
  - pip install -v .
script: nosetests tests
